export const ProfessionalStatus = {
  INDEPENDENT_PRIVATE_DOCTOR: 'INDEPENDENT_PRIVATE_DOCTOR',
  OTHER: 'OTHER',
  PRIVATE_GROUP_CABINET: 'PRIVATE_GROUP_CABINET',
  PRIVATE_INDIVIDUAL_CABINET: 'PRIVATE_INDIVIDUAL_CABINET',
  PUBLIC_WITH_COMPLEMENTARY_ACTIVITY: 'PUBLIC_WITH_COMPLEMENTARY_ACTIVITY',
} as const;

export type ProfessionalStatus =
  (typeof ProfessionalStatus)[keyof typeof ProfessionalStatus];
