export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN_VERIFICATION: 'ADMIN_VERIFICATION',
  ESTABLISHMENT_ADMIN: 'ESTABLISHMENT_ADMIN',
  AFFILIATED_DOCTOR: 'AFFILIATED_DOCTOR',
  INDEPENDENT_DOCTOR: 'INDEPENDENT_DOCTOR',
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];
