// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Optional. An empty database that Prisma may wipe: CI replays the
    // migrations there to check that they match schema.prisma.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
