import { type AiModel } from "./ai-analyses.types";

// Single source of truth of the AI models shown in HealixDZ, as described by
// the model team (October 2026). Only what they provided is filled in: every
// other fact stays null and the UI shows "non renseigné". In particular no
// metric may be added without its source (see ai-models.registry.test.ts).
// Names and intended uses are translated under aiAnalyses.models.<id>.
export const aiModels = [
  // --- Brain -----------------------------------------------------------------
  {
    id: "brain-efficientnetb4-tumor-classification",
    module: "brain",
    version: "1.0",
    architecture: "EfficientNetB4",
    task: "classification",
    inputModality: "brainMri2d",
    acceptedFormats: null,
    // The model's raw output labels.
    outputClasses: ["glioma", "meningioma", "notumor", "pituitary"],
    metrics: [
      { key: "cvAccuracy", value: 0.9927, unit: "percent", approximate: true, dataset: null },
      { key: "auc", value: 0.99, unit: "score", approximate: true, dataset: null },
    ],
    trainingData: null,
    knownLimitations: ["notCertified", "internalValidation", "closedSet", "singleSlice"],
    underrepresentedPopulations: null,
    status: "available",
  },
  {
    id: "brain-unet-glioma-segmentation",
    module: "brain",
    version: "1.0",
    architecture: "U-Net",
    task: "segmentation",
    inputModality: null,
    acceptedFormats: null,
    outputClasses: ["glioma"],
    metrics: [{ key: "dice", value: 0.9, unit: "score", approximate: true, dataset: null }],
    trainingData: null,
    knownLimitations: ["notCertified", "internalValidation"],
    underrepresentedPopulations: null,
    status: "available",
  },
  {
    id: "brain-unet-meningioma-segmentation",
    module: "brain",
    version: "5",
    architecture: "U-Net",
    task: "segmentation",
    // BRISC 2025 is a brain MRI dataset.
    inputModality: "brainMri",
    acceptedFormats: null,
    outputClasses: ["meningioma"],
    metrics: null,
    trainingData: "BRISC 2025",
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "available",
  },
  {
    id: "brain-unet-pituitary-segmentation",
    module: "brain",
    version: "5",
    architecture: "U-Net",
    task: "segmentation",
    inputModality: "brainMri",
    acceptedFormats: null,
    outputClasses: ["pituitary"],
    metrics: null,
    trainingData: "BRISC 2025",
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "available",
  },
  {
    id: "brain-flair-segmentation",
    module: "brain",
    version: "4",
    architecture: null,
    task: "segmentation",
    // Sequences as given by the model team ("T1ce → FLAIR").
    inputModality: "brainMriT1ceToFlair",
    acceptedFormats: null,
    outputClasses: [],
    metrics: null,
    trainingData: null,
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "available",
  },
  // --- Cardiology ------------------------------------------------------------
  {
    id: "cardiology-densenet121-chest-xray",
    module: "cardiology",
    version: null,
    architecture: "DenseNet121",
    task: "classification",
    inputModality: "chestXray",
    acceptedFormats: null,
    outputClasses: ["normal", "cardiomegaly", "effusion", "edema"],
    metrics: null,
    trainingData: null,
    knownLimitations: ["notCertified", "closedSet", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "available",
  },
  {
    id: "cardiology-acdc-segmentation",
    module: "cardiology",
    version: null,
    architecture: null,
    task: "segmentation",
    // ACDC is the cine-MRI cardiac segmentation dataset.
    inputModality: "cardiacCineMri",
    acceptedFormats: null,
    outputClasses: ["leftVentricle", "rightVentricle", "myocardium"],
    metrics: null,
    trainingData: "ACDC",
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "in_design",
  },
  {
    id: "cardiology-ct-heart-segmentation",
    module: "cardiology",
    version: null,
    architecture: null,
    task: "segmentation",
    inputModality: "cardiacCt",
    acceptedFormats: null,
    outputClasses: [],
    metrics: null,
    trainingData: null,
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "in_design",
  },
  // --- Pathology -------------------------------------------------------------
  {
    id: "pathology-hovernet-nuclei-segmentation",
    module: "pathology",
    version: null,
    architecture: "HoVer-Net",
    task: "segmentation",
    inputModality: "histopathology",
    acceptedFormats: null,
    outputClasses: ["nuclei"],
    metrics: null,
    trainingData: null,
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "exploring",
  },
  {
    id: "pathology-breakhis-classification",
    module: "pathology",
    version: null,
    architecture: null,
    task: "classification",
    // BreakHis is a breast histopathology image dataset.
    inputModality: "histopathology",
    acceptedFormats: null,
    outputClasses: [],
    metrics: null,
    trainingData: "BreakHis",
    knownLimitations: ["notCertified", "undocumentedPerformance"],
    underrepresentedPopulations: null,
    status: "exploring",
  },
] as const satisfies readonly AiModel[];

export type AiModelId = (typeof aiModels)[number]["id"];
