import {
  type AccountType,
  type SubscriptionPlan,
} from "@/types/subscription";

export const doctorSubscriptionPlans: SubscriptionPlan[] = [
  {
    accountType: "INDEPENDENT_DOCTOR",
    annualPrice: 29000,
    currency: "DZD",
    description: "subscription.plans.doctor.starter.description",
    features: [
      "subscription.plans.doctor.starter.features.dashboard",
      "subscription.plans.doctor.starter.features.patients",
      "subscription.plans.doctor.starter.features.consultations",
      "subscription.plans.doctor.starter.features.reports",
      "subscription.plans.doctor.starter.features.ai",
      "subscription.plans.doctor.starter.features.support",
    ],
    id: "DOCTOR_STARTER",
    limits: [
      "subscription.plans.doctor.starter.limits.patients",
      "subscription.plans.doctor.starter.limits.ai",
      "subscription.plans.doctor.starter.limits.users",
      "subscription.plans.doctor.starter.limits.reports",
    ],
    monthlyPrice: 2900,
    name: "subscription.plans.doctor.starter.name",
  },
  {
    accountType: "INDEPENDENT_DOCTOR",
    annualPrice: 59000,
    badge: "subscription.badges.popular",
    currency: "DZD",
    description: "subscription.plans.doctor.pro.description",
    features: [
      "subscription.plans.doctor.pro.features.allStarter",
      "subscription.plans.doctor.pro.features.unlimitedPatients",
      "subscription.plans.doctor.pro.features.advancedAi",
      "subscription.plans.doctor.pro.features.detailedReports",
      "subscription.plans.doctor.pro.features.longitudinal",
      "subscription.plans.doctor.pro.features.exportPdf",
      "subscription.plans.doctor.pro.features.prioritySupport",
    ],
    id: "DOCTOR_PRO",
    limits: [
      "subscription.plans.doctor.pro.limits.patients",
      "subscription.plans.doctor.pro.limits.ai",
      "subscription.plans.doctor.pro.limits.users",
      "subscription.plans.doctor.pro.limits.reports",
    ],
    monthlyPrice: 5900,
    name: "subscription.plans.doctor.pro.name",
    recommended: true,
  },
  {
    accountType: "INDEPENDENT_DOCTOR",
    annualPrice: 99000,
    currency: "DZD",
    description: "subscription.plans.doctor.premium.description",
    features: [
      "subscription.plans.doctor.premium.features.allPro",
      "subscription.plans.doctor.premium.features.premiumAi",
      "subscription.plans.doctor.premium.features.segmentation",
      "subscription.plans.doctor.premium.features.comparison",
      "subscription.plans.doctor.premium.features.priorityAi",
      "subscription.plans.doctor.premium.features.support",
    ],
    id: "DOCTOR_PREMIUM_AI",
    limits: [
      "subscription.plans.doctor.premium.limits.patients",
      "subscription.plans.doctor.premium.limits.ai",
      "subscription.plans.doctor.premium.limits.modules",
      "subscription.plans.doctor.premium.limits.support",
    ],
    monthlyPrice: 9900,
    name: "subscription.plans.doctor.premium.name",
  },
];

export const establishmentSubscriptionPlans: SubscriptionPlan[] = [
  {
    accountType: "ESTABLISHMENT",
    annualPrice: 149000,
    currency: "DZD",
    description: "subscription.plans.establishment.basic.description",
    features: [
      "subscription.plans.establishment.basic.features.dashboard",
      "subscription.plans.establishment.basic.features.patients",
      "subscription.plans.establishment.basic.features.doctors",
      "subscription.plans.establishment.basic.features.reports",
      "subscription.plans.establishment.basic.features.ai",
      "subscription.plans.establishment.basic.features.support",
    ],
    id: "EST_BASIC_CLINIC",
    limits: [
      "subscription.plans.establishment.basic.limits.doctors",
      "subscription.plans.establishment.basic.limits.patients",
      "subscription.plans.establishment.basic.limits.ai",
      "subscription.plans.establishment.basic.limits.sites",
    ],
    monthlyPrice: 14900,
    name: "subscription.plans.establishment.basic.name",
  },
  {
    accountType: "ESTABLISHMENT",
    annualPrice: 299000,
    badge: "subscription.badges.recommended",
    currency: "DZD",
    description: "subscription.plans.establishment.pro.description",
    features: [
      "subscription.plans.establishment.pro.features.allBasic",
      "subscription.plans.establishment.pro.features.doctors",
      "subscription.plans.establishment.pro.features.unlimitedPatients",
      "subscription.plans.establishment.pro.features.advancedAi",
      "subscription.plans.establishment.pro.features.detailedReports",
      "subscription.plans.establishment.pro.features.services",
      "subscription.plans.establishment.pro.features.support",
    ],
    id: "EST_PRO_CENTER",
    limits: [
      "subscription.plans.establishment.pro.limits.doctors",
      "subscription.plans.establishment.pro.limits.patients",
      "subscription.plans.establishment.pro.limits.ai",
      "subscription.plans.establishment.pro.limits.services",
    ],
    monthlyPrice: 29900,
    name: "subscription.plans.establishment.pro.name",
    recommended: true,
  },
  {
    accountType: "ESTABLISHMENT",
    annualPrice: 599000,
    currency: "DZD",
    description: "subscription.plans.establishment.enterprise.description",
    features: [
      "subscription.plans.establishment.enterprise.features.allPro",
      "subscription.plans.establishment.enterprise.features.doctors",
      "subscription.plans.establishment.enterprise.features.premiumAi",
      "subscription.plans.establishment.enterprise.features.segmentation",
      "subscription.plans.establishment.enterprise.features.roles",
      "subscription.plans.establishment.enterprise.features.audit",
      "subscription.plans.establishment.enterprise.features.support",
      "subscription.plans.establishment.enterprise.features.fhir",
    ],
    id: "EST_ENTERPRISE",
    limits: [
      "subscription.plans.establishment.enterprise.limits.doctors",
      "subscription.plans.establishment.enterprise.limits.patients",
      "subscription.plans.establishment.enterprise.limits.ai",
      "subscription.plans.establishment.enterprise.limits.services",
    ],
    monthlyPrice: 59900,
    name: "subscription.plans.establishment.enterprise.name",
  },
  {
    accountType: "ESTABLISHMENT",
    annualPrice: null,
    currency: "DZD",
    custom: true,
    description: "subscription.plans.establishment.custom.description",
    features: [
      "subscription.plans.establishment.custom.features.offer",
      "subscription.plans.establishment.custom.features.multisite",
      "subscription.plans.establishment.custom.features.fhir",
      "subscription.plans.establishment.custom.features.support",
      "subscription.plans.establishment.custom.features.sla",
      "subscription.plans.establishment.custom.features.accompaniment",
      "subscription.plans.establishment.custom.features.deployment",
    ],
    id: "EST_CUSTOM",
    limits: [
      "subscription.plans.establishment.custom.limits.scope",
      "subscription.plans.establishment.custom.limits.integration",
      "subscription.plans.establishment.custom.limits.support",
    ],
    monthlyPrice: null,
    name: "subscription.plans.establishment.custom.name",
  },
];

export function getSubscriptionPlansByAccountType(accountType: AccountType) {
  return accountType === "ESTABLISHMENT"
    ? establishmentSubscriptionPlans
    : doctorSubscriptionPlans;
}
